// Generated by the Avalanche control panel, do not edit by hand.
window.AVALANCHE_CONTENT = {
  "generated": "2026-08-23 05:47",
  "site": {
    "motto": "Truth falls like snow and accumulates",
    "tagline": "Independent · Anonymous · Unstoppable",
    "investigation": {
      "number": "001",
      "title": "",
      "stage": "Sourcing & verification",
      "opened": "August 2026",
      "blurb": "An investigation is currently underway. The subject stays secret on purpose. Announcing targets too early burns sources and evidence."
    },
    "notices": [
      "Investigation №001 is underway. It publishes when it’s ready",
      "This site collects nothing: no cookies, no analytics, no server logs",
      "Questions welcome. Ask anonymously through the drop box"
    ],
    "mirrors": [
      "https://seattleavalanche.online/"
    ]
  },
  "posts": [],
  "answers": [
    {
      "id": "AV-20260823-Q2JJPL",
      "alias": "asdasd",
      "question": "asdasdasdasd",
      "answer": "whats up fella",
      "date": "2026-08-23 05:40"
    }
  ],
  "tips": [
    {
      "id": "AV-20260823-Q2JJPL",
      "received": "2026-08-23 05:39 UTC",
      "topic": "tip",
      "alias": "asdasd",
      "contact": "asdasd",
      "message": "asdasdasdasd",
      "allow_public": 1,
      "files": [],
      "read": true,
      "reply": {
        "text": "whats up fella",
        "date": "2026-08-23 05:40",
        "published": true
      }
    }
  ]
};
