// Generated by the Avalanche control panel, do not edit by hand.
window.AVALANCHE_CONTENT = {
  "generated": "2026-08-23 05:27",
  "site": {
    "motto": "Truth falls like snow and accumulates",
    "tagline": "Independent · Anonymous · Unstoppable",
    "investigation": {
      "number": "001",
      "title": "",
      "stage": "Sourcing & verification",
      "opened": "August 2026",
      "blurb": "An investigation is currently underway. The subject stays secret on purpose. Announcing targets too early burns sources and evidence."
    },
    "notices": [
      "Investigation №001 is underway. It publishes when it’s ready",
      "This site collects nothing: no cookies, no analytics, no server logs",
      "Questions welcome. Ask anonymously through the drop box"
    ],
    "mirrors": [
      "https://seattleavalanche.online/"
    ]
  },
  "posts": [
    {
      "slug": "test-2",
      "title": "Test 2",
      "dek": "asdasd",
      "date": "2026-08-23",
      "status": "published",
      "tags": [
        "politics"
      ],
      "body_raw": "Test 2asdasd",
      "body_html": "<p>Test 2asdasd</p>"
    },
    {
      "slug": "test",
      "title": "Test",
      "dek": "Test",
      "date": "2026-08-21",
      "status": "published",
      "tags": [
        "Test"
      ],
      "body_html": "<p>Test</p>"
    }
  ],
  "answers": [],
  "tips": []
};
