// Generated by the Avalanche control panel, do not edit by hand.
window.AVALANCHE_CONTENT = {
  "generated": "2026-08-25 20:29",
  "site": {
    "motto": "Truth falls like snow and accumulates",
    "tagline": "Independent · Anonymous · Unstoppable",
    "investigation": {
      "number": "001",
      "title": "",
      "stage": "Sourcing & verification",
      "opened": "August 2026",
      "blurb": "An investigation is currently underway. The subject stays secret on purpose. Announcing targets too early burns sources and evidence."
    },
    "notices": [
      "Investigation №001 is underway. It publishes when it’s ready",
      "This site collects nothing: no cookies, no analytics, no server logs",
      "Questions welcome. Ask anonymously through the drop box"
    ],
    "mirrors": [
      "https://seattleavalanche.online/"
    ]
  },
  "posts": [
    {
      "slug": "story-1",
      "title": "Story 1",
      "dek": "Test",
      "date": "2026-08-25",
      "status": "published",
      "tags": [],
      "body_raw": "",
      "body_html": "<p></p>"
    }
  ],
  "answers": [],
  "tips": []
};
